[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting_system = "98eSBn9oRdJcPzFUuRMgktewygF6HfkwiCQUJuJBw1z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sergi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.devnet]
voting_system = "98eSBn9oRdJcPzFUuRMgktewygF6HfkwiCQUJuJBw1z"